### ISSUE TITLE
Wolfram2desmos v2

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#142]
https://github.com/Heavenira/wolfram2desmos/blob/main/wolfram2desmos%20v2.js

Check for `isIllegalASCIIMath` before pasting and pass off to the default Desmos handler if illegal (should help with the CSV crash)

Also add a boolean option for `reciprocalExponents2Surds`

**Comment by Heavenira** [comment]
I just added another "configuration", it is not a flag though. Rather, it is an integer.
```js
let derivativeLoopLimit = 3; // converts (d^#/dx^#) to (d/dx)... # times. 0=disabled
```
It would probably be too much to implement integer customizability in the UI... If this is not possible to do, then you could jump between 0 and 3 using a flag controller.
