### ISSUE TITLE
Pinned expressions nested in folders disappear when collapsing their parent folder

### ISSUE THREAD

**Issue by SlimRunner** [DesModder/DesModder#168]
As the title says. Admittedly is not that much of a problem in general as I can leave the smaller folders open to prevent the issue. However, large folders are a bit more annoying to keep open.

**Comment by jared-hughes** [comment]
Thanks for catching this!

Sample graph: https://www.desmos.com/calculator/6bqzhbqpe7. The collapsed folder contains a pinned expression, which is not shown.

As a temporary workaround, you could move pinned expressions out of folders.
