### ISSUE TITLE
Bug: Pasting any X_{Y}.Z becomes X_{Y.Z}

### ISSUE THREAD

**Issue by MarksonChen** [DesModder/DesModder#171]
Pasting something like 
![image](https://user-images.githubusercontent.com/46666959/127373890-aa4b3f9d-e11c-4b95-9801-0f09b4cc62f5.png)
gives
![image](https://user-images.githubusercontent.com/46666959/127373912-c12378d1-68cc-456a-a38f-e97df7d7ebef.png)
for anything in the form of X_{Y}.Z
When I disable this extension, the bug no longer appears.

**Comment by jared-hughes** [comment]
Thanks for sending this in.

As a temporary workaround, you can disable the Wolfram To Desmos plugin:
![image](https://user-images.githubusercontent.com/20214911/127443386-ff66e5ec-58ae-4c25-8e6f-159514832b39.png)

**Comment by jared-hughes** [comment]
Fixed by a71241ce778d31cc170ccfae4c99957358f26e7c
