### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by fadaaszhi** [DesModder/DesModder#205]
A form of putting variables in a namespace, possibly through folders, to prevent naming collisions / encourage cleaner code. An implementation might look like:
- Defining a namespace: a folder that the user wants to put in its own namespace would have the namespace resolution operator after the folder name followed by the namespace name: `<folder name>::<namespace name>`
- Accessing variables from another namespace: `<namespace name>::<variable name>`

**Comment by jared-hughes** [comment]
I love this idea.

It may be better to use dot access as the syntax to avoid potential confusion with piecewise `:`.

![image](https://user-images.githubusercontent.com/20214911/131980400-46026e88-2ce2-4048-89e0-3188e5ff92db.png)

**Comment by jared-hughes** [comment]
Text Mode now is designed to not add any new features, so this is more suited for other projects.
