### ISSUE TITLE
Give the plus-or-minus (±, \pm) and minus-or-plus (∓, \mp) signs functionality.

### ISSUE THREAD

**Issue by wompking** [DesModder/DesModder#210]
I am tired of having to write the Quadratic Equation with two parts, or by defining ± to be equal to [-1,1]. I think it would be extremely useful to have the ± and ∓ signs actually _work_; I'd suggest that they'd work somewhat like [this graph](https://www.desmos.com/calculator/np0isb7sby).

**Comment by jared-hughes** [comment]
I like this. Mathquill supports \mp and \pm as well; it just needs some work to automatically change `+-` into `±`.

![image](https://user-images.githubusercontent.com/20214911/132978360-2dca42ec-6378-42a9-a139-a10fed9298ab.png)
