### ISSUE TITLE
Retain table header root when duplicating

### ISSUE THREAD

**Issue by RannyBergamotte** [DesModder/DesModder#216]
When duplicating a table, the header in a column doesn't remain the same. If its in a folder however, it is fine.

**Comment by RannyBergamotte** [comment]
My only use case was when duplicating a table and i wanted to keep the original header variable names because they were pretty long, so i could just change 1 character in the header table instead of re-writing the header.

**Comment by jared-hughes** [comment]
Keeping the original header names is a good idea.
