### ISSUE TITLE
Lock viewport by axis

### ISSUE THREAD

**Issue by RannyBergamotte** [DesModder/DesModder#274]
I would love if we could lock viewport on only a certain axis, could be useful for like working on scrolling animations, although very few people would need it. Just an idea for a little improvement.

**Comment by jared-hughes** [comment]
Could you give an example of how this could be used?

**Comment by RannyBergamotte** [comment]
The only reason that i would see possibly is for working with scrolling animations or something, or like a scroll puzzle. 
Therecould also certainly other random reasons it would be useful. 
Prob should be put at the bottoms of to do list though I imagine, would be rare that anyone would really really need it.

**Comment by jared-hughes** [comment]
Bottom of to-do list indeed. I'll close this as not-planned for now.
