### ISSUE TITLE
Real Dark/Night Mode/Theme

### ISSUE THREAD

**Issue by Zi7ar21** [DesModder/DesModder#283]
Desmos by default has neat colors and stuff but has a big problem: It uses gross, awful, terrible, eye-frying light mode. What can you currently do about it? Well, there is a "Reverse Contrast" option but it looks terrible. It uses high contrast colors that are harsh on the eyes. What would be ideal? Well just replacing the light background with a nice dark one and keeping the pleasant colors, plus possibly changing them a little to make them stand out from the dark background if they already don't. (not entirely inverting them like reverse contrast!) I don't know if Desmos is going to officially fix this issue, but it would be great for this project as the point of this extension is to fix and improve things.

**Comment by jared-hughes** [comment]
Wonderful idea. Yes, it would be in the scope of the extension, but other great options exist, so it probably will not be added directly to DesModder.

I personally recommend the [Dark Reader extension](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh).

Fasteroid also made a [user stylesheet](https://www.reddit.com/r/desmos/comments/o4cq86/dark_theme_user_stylesheet_for_desmos/).

Pic below is while using Dark Reader:
![image](https://user-images.githubusercontent.com/20214911/144552204-9ac65631-c8c3-48b0-b0c3-477828d557e4.png)
