### ISSUE TITLE
Find and replace overwrites exponents

### ISSUE THREAD

**Issue by MathEnthusiast314** [DesModder/DesModder#284]
https://www.desmos.com/calculator/2ttaopcbwy
replacing s_{l} with `(a+b)` doesn't yield `(a+b)^2` in expression 4 but just yields `(a+b)`.
I noticed this error while replacing variables having subscripts.

**Comment by jared-hughes** [comment]
Thanks for the report! This is strange behavior. Will take some investigation to figure out what's causing it.

**Comment by jared-hughes** [comment]
https://www.desmos.com/calculator/8vfeo1yqsh
