### ISSUE TITLE
Auto-save

### ISSUE THREAD

**Issue by RannyBergamotte** [DesModder/DesModder#288]
Auto-saves your graph every 5 min or so (maybe controllable?). Even though Desmos has a recovery option now, in some cases it can still fail. 
Also could be interesting to have an autosave feature stored inside Desmodder in case you get disconnected from the internet.

**Comment by jared-hughes** [comment]
I've never had any issues with the recovery feature. You can enable `?fastAutoSave` if the 5-minutes default is too slow.

Can you share instances where the recovery feature didn't work with the Desmos team? No need to duplicate features.

**Comment by RannyBergamotte** [comment]
Yep sounds good!
Slept on it a bit, and then today it happened. 
Basically connected on hotspot, and then must have disconnected for a bit. 10 min later, accidentally closed the tab and then tried recovering and it failed.

I'll send an email to the Desmos team.
