### ISSUE TITLE
Desmos WakaTime Support

### ISSUE THREAD

**Issue by Heavenira** [DesModder/DesModder#299]
[The Tampermonkey script abandons the proxy!](https://github.com/Heavenira/desmos-wakatime)

It would be great if the secret key can be pasted as text in the DesModder context menu.

**Comment by Scoder12** [comment]
I'm working on this.

**Comment by Heavenira** [comment]
:O
I await eagerly for its arrival!!! Getting my WakaTime subscription prepared :)
