### ISSUE TITLE
GLesmos doesn't support color css functions or named colors

### ISSUE THREAD

**Issue by SlimRunner** [DesModder/DesModder#302]
This is kind of a niche issue since the new latex color scheme has superseded the old way of overriding the "color" attribute of expressions through the console.

Anyway, the code seems to do something with the invalid input. Some rgb or rgba combinations result in dark blue hues. [Here is a test graph ](https://www.desmos.com/calculator/ieiouwmu63). I'm not aware if you are able to harness Desmos' built-in color parsing as Desmos seems to just work fine with most non-experimental formats.

If that's not the case I'm sure a dedicated library is a sound solution, but I have previously written a somewhat decent parser in the form of several functions which might be just put into a module provisionally. Relevant code here [dgc-art-tools.user.js#L2287-L2745](https://github.com/SlimRunner/desmos-scripts-addons/blob/41889a2cebd141710ab5f0ba3d9c5797c1d9a3ee/art-tools-script/dgc-art-tools.user.js#L2287-L2745)

**Comment by SlimRunner** [comment]
Update on the issue. I took the time to transpile my code to TS and have a working branch in my fork. I need to do some testing before I make a pull request.

Also, I have a concern. While the parsing function is not overly complex it adds some overhead and it seems the color is requested each time the graph paper refreshes. It doesn't add any visible lag in my testing so far, but it is something to consider. Also, I might have put the parsing function the wrong place. I replaced these lines [outputHelpers.ts#L11-L13](https://github.com/DesModder/DesModder/blob/e4bc7beee8cbad1cf9d7416478408dd5ec969e6a/src/plugins/GLesmos/outputHelpers.ts#L11-L13)

**Comment by jared-hughes** [comment]
Yes, that looks like the right place to change the color. With regard to your performance concern, you can have an early-out if the color string starts with `#` and is seven characters long. Then the overhead would be negligible for most graphs.
