### ISSUE TITLE
Suggestion: Info display

### ISSUE THREAD

**Issue by GanerCodes** [DesModder/DesModder#318]
An option to enable certain info such as mouse location on graph, framerate (I know you can use url tricks but a toggle would be better), etc. would be nice to have

**Comment by jared-hughes** [comment]
Could you clarify what you mean by mouse location on graph? Do you want a variable that gets continuously updated with the position of the mouse?

The framerate + performance is already planned, e.g. https://github.com/DesModder/DesModder/issues/45 and https://github.com/DesModder/DesModder/issues/307.

Do you have any other suggestions collapsed into "etc."?

**Comment by GanerCodes** [comment]
> Could you clarify what you mean by mouse location on graph? Do you want a variable that gets continuously updated with the position of the mouse?

I mean sorta like the fps counter you can see the exact coordinate your mouse location is on the graph, it's faster and more accurate than looking at the gridlines

**Comment by jared-hughes** [comment]
Oh that's a great idea! In some situations, it can be much better than messing around with dragging points.

I'm currently envisioning a HUD where you can choose from various readouts, including:

- xy mouse position
- FPS
- Time in Worker

**Comment by GanerCodes** [comment]
That sounds awesome, thanks!

**Comment by jared-hughes** [comment]
Resolved by #412 (performance view). XY mouse position doesn't help too much because draggable points also work, so that sub-request is declined for now.
