### ISSUE TITLE
Slider custom speed feature request

### ISSUE THREAD

**Issue by RannyBergamotte** [DesModder/DesModder#323]
After seeing your answer in #help-questions on the Desmos discord
https://discord.com/channels/655972529030037504/663607163532476426/936409412166357002
could be nice to have a way to allow the user to input any number for the slider speed (maybe through the use of a text box or something in the expression option)

**Comment by jared-hughes** [comment]
Great idea!

**Comment by jared-hughes** [comment]
Resolved with Text Mode (#373). A better UI is possible but probably not worth time
