### ISSUE TITLE
Desmos crashes in Firefox when opening graph link and forcing a new tab

### ISSUE THREAD

**Issue by SlimRunner** [DesModder/DesModder#325]
To reproduce this issue `ctrl`+`click` on a graph link in Firefox. As it loads in the background something fails and the error message pops up first in the web console:

> Uncaught Error: Couldn't find a style target. This probably means that the value for the 'insert' parameter is invalid.

Test link: [https://www.desmos.com/calculator/uqrizmcrot](https://www.desmos.com/calculator/uqrizmcrot)

Extra notes: the issue seems to be linked to Firefox way of forcing a new tab with user override because a link with target _blank will open without problem, but it will fail if it's user-overridden to open in a new tab anyway. I could not reproduce the issue in Chrome, so I have assumed it's related to Firefox. Test was made on Firefox 96.0.3 in Windows.

**Comment by SpaceDevz** [comment]
Can't replicate, works fine in my testing

**Comment by jared-hughes** [comment]
This appears to be fixed from the recent loading system changes.
