### ISSUE TITLE
WolframAlpha paste not working in Firefox

### ISSUE THREAD

**Issue by daver1691** [DesModder/DesModder#329]
Cut-and-paste modification of WolframAlpha's "copyable plain text" does not work on Firefox (using ctrl-v to paste). 
Tested with Windows Firefox 97.0 and Ubuntu Firefox 96.0. 

(It _does_ work on Chromium.)

**Comment by jared-hughes** [comment]
I can reproduce this on Ubuntu Firefox 97.0

**Comment by jared-hughes** [comment]
I can no longer reproduce, on Firefox 110. Assuming it's fixed.
