### ISSUE TITLE
Edit Table in Pin Mode

### ISSUE THREAD

**Issue by RannyBergamotte** [DesModder/DesModder#335]
You cannot select any cell of a table who is being pinned. You can edit them, but you can't select and use the arrow keys in the table.

**Comment by RannyBergamotte** [comment]
Huh, played around a little bit more, somehow I got multiple text cursors, by clicking in the pinned table and then using arrow keys to move along text in the expression list on a folder

**Comment by jared-hughes** [comment]
I can no longer reproduce this. Assuming it's been fixed.
