### ISSUE TITLE
"[" sometimes resets cursor position (textmode)

### ISSUE THREAD

**Issue by FenyLabs** [DesModder/DesModder#382]
Typing "[" in expression bodies will sometimes cause the cursor to reset to the beginning of the line. A very basic example can be seen by typing "a=[" or "a = [". The end square bracket will be inserted automatically and the cursor will reset to the beginning of the line.

Browser: Chrome

**Comment by jared-hughes** [comment]
I have a half-baked solution in the form of the following code (swap out in `modify.ts`). But it is whitespace-dependent (works for `a = [` but not `a=[`) and overall a hack. I'd rather address the underlying cause, #393.
```ts
function insertWithIndentation(
  view: EditorView,
  pos: TextAST.Pos,
  insert: string
) {
  const indentation = getIndentation(view, pos.from);
  insert = insert.replace(/\n/g, "\n" + indentation);
  const head = view.state.selection.main.head;
  if (
    pos.from <= head &&
    head <= pos.to &&
    view.state.sliceDoc(pos.from, head) === insert.slice(0, head - pos.from)
  ) {
    return {
      from: head,
      to: pos.to,
      insert: insert.slice(head - pos.from),
    };
  }
  return {
    from: pos.from,
    to: pos.to,
    insert,
  };
}
```
