### ISSUE TITLE
Loading failure when tab is not active (Firefox)

### ISSUE THREAD

**Issue by SinclaM** [DesModder/DesModder#397]
On Firefox (102.0.1), DesModder will fail to load if a Desmos tab is refreshed while not being the active tab.

To reproduce, open two tabs, with the Desmos graphing calculator in one of them. Navigate to the other tab, then reload the now inactive Desmos tab. Wait a second or two, then navigate back to the Desmos tab, and it will fail to load due to an error loading a style.

https://user-images.githubusercontent.com/82351204/180488639-a964bab2-5fd9-4535-86a0-cf3a705a1de7.mov

After some testing, it doesn't seem to fail always, but it's common enough to be easily reproducible. I'm not sure how relevant this issue is; I doubt many users would ever need (or even try) to reload the tab while it's not active, but I felt like it's worth mentioning, especially since here DesModder doesn't fail gracefully like in other cases.

**Comment by jared-hughes** [comment]
Interesting. I can reproduce this. It's a niche bug as you say, but it might indicate a larger problem such as a race condition.

**Comment by SinclaM** [comment]
Oh, this is a duplicate of #325.

**Comment by jared-hughes** [comment]
This appears to be fixed from the recent loading system changes.
