### ISSUE TITLE
Functions: sigma, etc

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#40]
see https://docs.google.com/document/d/e/2PACX-1vQ7r4G_W7UfbUup_RlyRytcSi9nYAN8Hf1Ev8ZVTVpUmZbFsfud8e47CVp3rAisW4cwOS1ZzG6hC4kS/pub

great ideas; might be able to be implemented via plugin

Related: #38

**Comment by FabriceNeyret** [comment]
uh, the link above seems to be a different copy than https://docs.google.com/document/d/10RXB3Og8UQd3j9qJVTlPqAGT9z4Np73PocKeb6upGzU/edit
https://docs.google.com/document/d/1euP3NC18LKQWebVq-tvE1ENkJRZMz6bTsQWAwKdXahc/edit?usp=sharing
where I added some stuff !
( basically, I added ( ref to ) my own list https://docs.google.com/document/d/10RXB3Og8UQd3j9qJVTlPqAGT9z4Np73PocKeb6upGzU/edit?usp=sharing )
