### ISSUE TITLE
Cache Babel output in extension storage until hash changes

### ISSUE THREAD

**Issue by FenyLabs** [DesModder/DesModder#401]
Currently Babel transformations are run on calculator.js every time the page loads, while they only need to be run once per update. Consider caching the output to a file in extension storage until the hash in the filename changes.

**Comment by Scoder12** [comment]
Since the transformations are dependent on settings, it should also store a checksum of the settings, such as a non-cryptographic hash function like md5, inorder to invalidate the cache when the settings change.

**Comment by jared-hughes** [comment]
The overrides themselves are not dependent on settings; they generate the same code regardless of user settings. The settings are checked at runtime. Even if the page is loaded with some extensions disabled, the code doesn't need to be re-generated when the user changes settings.

**Comment by jared-hughes** [comment]
Resolved by https://github.com/DesModder/DesModder/commit/ff440c5ff13cd6a7c075fbb81d7cdb603a511b17, (and there are now user settings for changing compilation, but they are only made available in case of panic -- a failed replacement)
