### ISSUE TITLE
Plugin Categories

### ISSUE THREAD

**Issue by FenyLabs** [DesModder/DesModder#405]
As plugins continue to be added, the list has become quite long and unorganized. I propose categorizing the plugins by how much they change Desmos. You could also consider sorting by frequency of use so that the most-used plugins are at the top of each category. Plugins that you would never turn off (ex. shift-enter newline, right-click tray) might go at the bottom of a category.

Core - Significantly changes or adds functionality (Impossible in vanilla Desmos):
- Calculator Settings
- Video Creator
- GLesmos
- Text Mode

Utility - Provides useful tools that make difficult tasks easier (Difficult in vanilla Desmos):
- Wolfram to Desmos
- Pin Expressions
- Find and Replace
- Right Click Tray
- Duplicate Expression Hotkey
- Shift-Enter Newline
- Folder Tools

Visual - Changes the visual look of the calculator or adds information:
- Set Primary Color
- Debug Mode
- Show Tips
- Hide Errors

**Comment by jared-hughes** [comment]
Great ideas. I guess the upcoming Performance View plugin can go in Utility as well?
