### ISSUE TITLE
Sort imports

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#413]
Prettier is good at avoiding merge conflicts in general, but it would be good to also sort imports to avoid more conflicts.

A prettier plugin for this: https://github.com/trivago/prettier-plugin-sort-imports

This could also be done through eslint, but we're not using any linter currently.

Inspired by @Scoder12

**Comment by Scoder12** [comment]
Personally, I use VS Code's "Organize imports on save" if that helps
