### ISSUE TITLE
Copy out from expressions with ASCII Math. This makes it more readable when shared.

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#42]
Maybe put this into wolfram2desmos as an inverse operation?

The concept is that we could send `a+b/(c+d/e)` in chats instead of `a+\frac{b}{c+\frac{d}{e}}`. The former is much more readable without having to paste into Desmos.

If desmos-latex → ASCIIMath can be made to preserve enough information, this could completely replace latex from a user's point-of-view.

Make it forwards compatible with DesmosPlus if possible; this mostly means always use `*` for multiplication (no implicit).

**Comment by Heavenira** [comment]
https://github.com/Heavenira/desmos2ascii
It is officially ready to roam the wild! :)

**Comment by jared-hughes** [comment]
Resolved with #373
