### ISSUE TITLE
The radical notation module is not working

### ISSUE THREAD

**Issue by Mehmet41** [DesModder/DesModder#463]
I tried to paste in 3^(1/4) with the mod turned on, it appeared as \sqrt{\left[4\right]}3
I expected \sqrt[4]{3} instead

Exemple:
<img width="199" alt="image" src="https://user-images.githubusercontent.com/51716593/205864578-cd4dfb28-2e77-4973-9f46-c721fb38ee1c.png">

**Comment by jared-hughes** [comment]
Thanks for reporting. This probably occurred due to some substitutions out of order. @Heavenira could you take a look?
