### ISSUE TITLE
When exiting the CTRL+F menu, keep the current selection.

### ISSUE THREAD

**Issue by Heavenira** [DesModder/DesModder#466]
This affects even vanilla Desmos. Plz fix, much gratitude. ❤️

*To reproduce this issue:* Search anything. Select any expression. Exit search menu. Now expression 1 is highlighted, for some reason.

Can you make it stay on the previously selected expression?

**Comment by jared-hughes** [comment]
It's fixed! :tada:

**Comment by Heavenira** [comment]
Yay! :)  I actually don't remember, has this been fixed by Desmos officially or did you just get around to it 🤣

**Comment by jared-hughes** [comment]
Both
