### ISSUE TITLE
Error: Require is not defined

### ISSUE THREAD

**Issue by meutzitzu** [DesModder/DesModder#468]
![image](https://user-images.githubusercontent.com/35000057/208596906-d912e768-7ad0-45c6-839c-adafb5920591.png)

idk what this means or how to fix it but Desmodder does not work at all (menu does not open) (even though it did in the past) on **Firefox 90.0 (64bit)**

**Comment by jared-hughes** [comment]
That error shouldn't be a problem. Have you tried updating Firefox? Latest version is 108, so your browser is a year and a half old.

If the update doesn't work: what error do you get when you click the menu?

**Comment by jared-hughes** [comment]
The error should no longer appear. Desmos has removed that script tag.
