### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'getCurrentGraphTitle')

### ISSUE THREAD

**Issue by Fasteroid** [DesModder/DesModder#471]
DesModder currently fails to load for [this](https://www.desmos.com/calculator/ujoqnwfnni) graph (and probably others!)
![image](https://user-images.githubusercontent.com/29342750/209571246-90d2d2a7-b09d-4892-9bb2-07cd031ffbaf.png)
This seems to have been introduced by https://github.com/DesModder/DesModder/commit/31c215c728a30c69b8f4861c5343a9fbf8aa958e.

**Comment by jared-hughes** [comment]
Resolved by b6de7f84094f26c7891be6ec60c6b454cc0e684a.
