### ISSUE TITLE
GLesmos quit working

### ISSUE THREAD

**Issue by MellowYellow7777** [DesModder/DesModder#499]
(apologies in advance, for github is unknown territory to me)

was just fractaling away with some semi-heavy glesmos renderings and it just broke and i cant seem to get it back. i tried removing / reinstalling and all the turn it off turn it on stuff but nothing.
vivaldi (/opera):
![Screen Shot 2023-02-11 at 4 31 06 AM](https://user-images.githubusercontent.com/81114382/218252864-fa25df35-9cf1-44c7-b892-2306d84731af.png)
firefox:
![Screen Shot 2023-02-11 at 4 31 10 AM](https://user-images.githubusercontent.com/81114382/218252866-045ddfec-6c1d-40f4-96e3-61da910f981f.png)

**Comment by jared-hughes** [comment]
No worries. Fasteroid fixed it a few commits ago in https://github.com/DesModder/DesModder/pull/495. The fix will likely be released properly in a few days, so just be patient for now.

I'll leave this issue open for now in case anyone else looks on the issues page.

**Comment by jared-hughes** [comment]
Update: the fix is released as of [v0.9.3](https://github.com/DesModder/DesModder/releases/tag/v0.9.3). The release is out on Firefox, but still pending (as usual :roll_eyes:) for Chrome approval.
