### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by FabriceNeyret** [DesModder/DesModder#50]
I could copy here the hundred of suggestions I gave to the team, but I guess we cannot really implement new functions or functionalities here as we want graphs to stay compatible with people not using the plugin, right ? ;-)

At least, while doing my DesmosGallery export script, I saw it is easy to also export the json of graphs, for instance if we want to save a backup out of Desmos (or maybe export one day to some Desmos clone, who knows ;-) ). My problem was that by default only 20 are loaded in the structure and I'm not experienced enough to find how to trigger populating the rest. But maybe you would know how to :-)

**Comment by jared-hughes** [comment]
I'm sure some of your suggestions are covered elsewhere in the [issues list](https://github.com/jared-hughes/DesModder/issues) (in fact, I think I attribute some to you). 

Regarding the "we cannot really implement new functions or functionalities here as we want graphs to stay compatible with people not using the plugin," I do have a planned system called graph dependencies that operates like DesThree's version warning system. An expression is inserted at the top if the graph depends on any new "functions or functionalities," so if someone doesn't have DesModder, it shows a warning for them. If someone does have DesModder, the warning is removed, and the graph proceeds as expected.

Regarding the exporting JSON of graphs, I might be able to figure out exporting, though it's not priority right now. You might want to provide some suggestions on #37 as to what format would be most helpful.

**Comment by FabriceNeyret** [comment]
try me :-) https://docs.google.com/document/d/10RXB3Og8UQd3j9qJVTlPqAGT9z4Np73PocKeb6upGzU/edit?usp=sharing

ok, most are out of range for you, or would destroy compatibility. But some could be done in the plugin. 
Eg: flag to recap that there is a hidden error in some folder. flag left to folder icon, + flag at graph top.

**Comment by jared-hughes** [comment]
If you only read two, read #20 for yourself and #8 to please clarify a question

1. line feed in comment sections: already implemented
1. naming greek letters: covered in the issue: https://github.com/DesModder/DesModder/issues/35
1. fract(x) = mod(x,1) → will not implement, too trivial
1. roll(L,n) = list offsetted by n with cycling. → will not implement, can be easily made in vanilla Desmos
1. offset(L,n) = list offsetted by n without cycling. → will not implement, can be easily made in vanilla Desmos
1. simple text-friendly option to copy-paste expressions  from/to outside: partially implemented in wolfram2desmos, but I hope to improve it with [DesmosText](https://github.com/jared-hughes/DesmosText)
1. Bessels functions → seems like it could be implemented through an integral? Either way, we can't throw every function in, as that would complicate stuff
1. point drag mode option also for lists (e.g. when displayed in table as in your https://www.desmos.com/calculator/zssfam7bgg )
   or points(list)  define with formula → not sure what you mean here. Are you referring to [constraining dragged points along a curve](https://www.desmos.com/calculator/rdyrrekat9) but on lists?
1.  in addition to cartesian and polar grid, what about adding log_x and log_y grids ? → Just added as https://github.com/DesModder/DesModder/issues/156
1. comparing points, like we can already compare lists → componentwise or checking if distance = 0? Other ways to define equality between points, so unlikely.
1.  Currently we can displays zeros of f(x) with 0=f(x) , or extrema with 0=d/dx f(x) . would it be possible to add a new command/syntax exporting these values in a array ? could be for instance   0=f(X) , where X is an array,    or solve{ 0=f(x), X } → won't implement, regressions already let you give one zero, and more zeroes are known to be a difficult problem, even when not having to consider the interface to Desmos
1. option to offset the rendering of a curve, without having to dirty its expression with (x-10)  or expr+5 to display tables of them → nah
1. Giving access to the unique url for the last version of a graph. The same that we see in our Desmos menu (but no url is available on right click, so alas ). → would require a separate server to store stuff, infeasible for the current extension setup
1.  Having the possibility to let others browse our graphs (or a chosen subset ) → I'd love this too, but we'll settle for the current standards of reddit + discord + custom sites for the same reasons as the previous point
1. Letting us order our graphs in the menu list.   → https://github.com/DesModder/DesModder/issues/44
1. we can get AND boolean operator by piling up   { cond } statements.   but it doesn't seem to have anything convenient to make a OR. BTW, what about implementing the logicals AND , OR , NOT in condition statements? → https://github.com/DesModder/DesModder/issues/157
1. there doesn't seem to have an easy way to do polar parametrics ? ( (r(t),theta(t) ) → `cis(t) = (cos(t),sin(t))`; `r(t) * cis(theta(t))` not too bad
1. for the sake of saving space in long graphs, typically to describe parameters, it would be convenient to be able to add comments inside equations. e.g. #comment + line break + equation or parameter def ,  or   #comment at the right of equation or parameter def. → Yeah multiline equations are [possible but difficult](https://github.com/jared-hughes/DesModder/issues/75). For the specific issue here of describing parameters, hopefully https://github.com/DesModder/DesModder/issues/64 will help.
1. and nested folders → https://github.com/DesModder/DesModder/issues/93

There were a few more duplicates on your doc but at the very bottom I just wanted to address:

20. several reciprocal functions are apparently missing:
  - for sinh, cosh, tanh → `arcsinh`, `arccosh`, and `arctanh` exist. (You may be interested in [full list of Desmos functions](https://www.reddit.com/r/desmos/comments/okz92t/list_of_all_desmos_functions_and_special_syntax/))
  - for erf → there's [normaldist inversecdf](https://www.desmos.com/calculator/sbaqduxzos)

**Comment by jared-hughes** [comment]
Everything appears to be resolved or put in a new issue. Closing for now
