### ISSUE TITLE
Glesmos not working

### ISSUE THREAD

**Issue by akshith108** [DesModder/DesModder#513]
![isue](https://user-images.githubusercontent.com/126483650/221577825-3a332f47-054f-481e-a866-4255d61dbc71.png)
Glesmos is not rendering it shows this warning when i enable glesmos

**Comment by jared-hughes** [comment]
The commit 64f786f240a76114530355f4deac6cab852b8e86, currently on main branch, fixes this issue. I am planning to release the fix to the extension stores within a few days.
