### ISSUE TITLE
Evaluation previews overflow easily

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#526]
![image](https://user-images.githubusercontent.com/20214911/223079790-e5cd4065-fd05-439f-9592-d7d440e9a9ed.png)

Some ideas:

- Over-complicate this by calculating widths, selecting truncation points, etc., and updating this as the expressions list changes width.
- Use whatever Desmos uses for the fading off to the right in normal expressions (and menus where you can edit latex). Maybe a bit more magic needed, but it'll be more robust.
- Fade away only part of the expression, e.g. `= 1000 element list ([0.1234,0.12359,0.23])` where the part in parentheses fades and is scrollable
- Two lines view like the result of `stats()` or `ttest()`
- Click into the preview and get more detail in something like a dropdown or a model ([:eye: eye preview idea](https://github.com/DesModder/DesModder/issues/458)).

**Comment by FenyLabs** [comment]
A potential idea? Imagine there was an eye in the circle and the lock wasn't there. Might have to split into multiple smaller paged expressions to avoid extreme lag and tiny scrollbars.

![conceptpre](https://user-images.githubusercontent.com/67439564/224623944-2b4805f7-a1bd-4677-9646-aaee5fd12570.png)
