### ISSUE TITLE
Menu too long

### ISSUE THREAD

**Issue by RannyBergamotte** [DesModder/DesModder#535]
When ui is zoomed in, cannot see bottom options, scrollbar or something is needed.

![image](https://user-images.githubusercontent.com/83847691/228106281-6bbae50a-28c9-48fa-9b1d-94ba8a7abbd1.png)

**Comment by jared-hughes** [comment]
![image](https://user-images.githubusercontent.com/20214911/228714597-ea37b5e8-fa27-4c68-a119-4b1ea3202736.png)

This is also a problem for tall screenshots.
