### ISSUE TITLE
example plugin broken

### ISSUE THREAD

**Issue by ronwnor** [DesModder/DesModder#549]
the plugin name/description are not shown :(
![image](https://user-images.githubusercontent.com/109063662/230679171-fd74c71c-41c3-43fe-b000-91a0d19ce47b.png)
I went through the other plugins' code, and looks like they all use stuff like `import { Plugin } from "plugins";`, which isn't on the example?

**Comment by jared-hughes** [comment]
Fixed by 7f38a8e117ccb051c8689144294fed224e6d623f. Thanks for bringing this up
