### ISSUE TITLE
Spaghetti Cleanup

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#556]
The main thing to do here is move methods from `main/Controller.ts` to their appropriate plugins. Stuff like `folderMerge()` or `canBeGLesmos()`.

Along with this, there could be improved ergonomics for accessing a plugin. `DesModder.controller.exposedPlugins["text-mode"]` is such a mouthful. Support something like `DesModder.plugin("text-mode")`.

**Comment by FenyLabs** [comment]
> Support something like DesModder.plugin("text-mode").

Would also love shorthands for plugin enabled and plugin option, to replace stuff like `window.DesModder?.controller?.isPluginEnabled?.("better-evaluation-view")` and `window.DesModder?.controller?.pluginSettings.get("better-evaluation-view").lists`

**Comment by RannyBergamotte** [comment]
Also I don't know if this is the place for this as part of cleanup, but adding the missing translation strings would be nice. I tried to do it for the missing tips but am still too dum at typescript.

**Comment by jared-hughes** [comment]
Ranny, I've marked that separately as #605
