### ISSUE TITLE
Horizonal Scrollbars For Expressions

### ISSUE THREAD

**Issue by ronwnor** [DesModder/DesModder#562]
feature request to add horizontal scrollbars to expressions 

something like this behaviour in the better eval plugin would be absolutely epic 
https://github.com/DesModder/DesModder/assets/109063662/bf2bfe7e-3447-420c-bf71-04b7570a1d32

**Comment by jared-hughes** [comment]
I love this idea!

**Comment by jared-hughes** [comment]
This is implemented in Better Navigation > Scrollable Expressions.
