### ISSUE TITLE
Chinese localization (zh-CN)

### ISSUE THREAD

**Issue by StaticReasons** [DesModder/DesModder#565]
May I add Chinese translation to DesModder? 
I'll be working on https://github.com/StaticReasons/DesModder/tree/translation-zh-CN, and complete the first edition within a few days.

**Comment by jared-hughes** [comment]
Sure! I'll merge it (after review) if you send a pull-request with zh-CN translations.

In case you haven't seen it, https://github.com/DesModder/DesModder/blob/main/docs/DEVELOPMENT.md#example-creating-a-new-translation-file covers how to set it up. Note `npm run audit-langs zh-CN` to check for mistakes.

**Comment by StaticReasons** [comment]
The first version is done over there: #600
