### ISSUE TITLE
I am getting an error that prevents Desmos from Evaluating equations

### ISSUE THREAD

**Issue by FearedFusionX** [DesModder/DesModder#604]
DesModder Returns these Errors:

```
DesModder Loading Errors Manager
Looks like some Desmos change happened to break some of DesModder's patches.
The patches are for the following purposes. Some may be critical, some may just be styling:
Compile GLesmos code instead of running implicit plotter
Override the evaluation view
Distinguish 0 vs -0 and NaN vs -∞ vs +∞
```

This impacts Desmos critically. I can't evaluate anything.

**Comment by FenyLabs** [comment]
This looks like the issue from 0.10.5

**Comment by FearedFusionX** [comment]
I am currently running on these specs: chromeOS Version 111.0.5563.118 (Official Build) (64-bit)
The version of the extension is v0.10.6.

**Comment by FearedFusionX** [comment]
Desmos started working again but I am still getting an error:
```
Compile GLesmos code instead of running implicit plotter
```
It's not impacting Desmos, however.
