### ISSUE TITLE
Preload failure in private window firefox

### ISSUE THREAD

**Issue by FenyLabs** [DesModder/DesModder#608]
Extension storage is forbidden in private windows, and trying to use desmodder in private windows causes a preload failure (perhaps during get-initial-data?). Haven't tested much, it's like 2 am and someone just posted screenshots in the discord.

**Comment by Why-not-now** [comment]
Comparison between incognito and normal:

Incognito:
![image](https://github.com/DesModder/DesModder/assets/81090788/92745ce1-e716-4f57-9fc9-5e5f276c968c)

Normal:
![image](https://github.com/DesModder/DesModder/assets/81090788/53f150de-d88f-46c5-8e5d-227cf43440a9)

**Comment by jared-hughes** [comment]
I assume this is due to `browser.storage` (or `chrome.storage`?) being undefined or something like that. Simple fix could be to replace `browser.storage.sync.get(props, callback)` with something like
```js
(browser.storage ?? {sync: {get: (props, callback) => callback(defaults)}}).sync.get(props, callback)
```

**Comment by jared-hughes** [comment]
Turns out it was IndexedDB
