### ISSUE TITLE
Replace variable function does not replace the lower limit of an integral

### ISSUE THREAD

**Issue by cd-CreepArghhh** [DesModder/DesModder#614]
Changing the name of a variable and then pressing the "rename variable --> new variable" button does not affect the lower limit of any integrals that have that variable. However, it affects the upper limit.

[Graph showcasing this bug](https://www.desmos.com/calculator/ezsfbebq8i)

I am not sure what the plugin is called, but it is not a part of Find and Replace.

**Comment by jared-hughes** [comment]
It's actually built-in to vanilla Desmos, though it's still a little buggy (as you noticed), so it's not officially released. Try typing "rename a->b" in the search bar, then clicking the little icon on the right.

![image](https://github.com/DesModder/DesModder/assets/20214911/378f4b95-7677-4b37-a621-9b529697865e)

(I've passed on this bug report to Desmos)

The suggestion to change the name of a variable only appears if you have author features enabled. Try disabling author features if the "rename a -> b" suggestion bothers you.

![image](https://github.com/DesModder/DesModder/assets/20214911/fcbc7e25-8fe9-46c4-96c0-ec7bd2e6f858)

**Comment by cd-CreepArghhh** [comment]
Since it's not an issue with DesModder should this issue be closed as not planned?
