### ISSUE TITLE
Compact View/Multiline Expressions options overflow

### ISSUE THREAD

**Issue by FenyLabs** [DesModder/DesModder#641]
The options for Compact View and Multiline Expressions overflow by default for me, creating a horizontal scrollbar
![23-07-06_5](https://github.com/DesModder/DesModder/assets/67439564/85a053da-5f75-487f-9615-c8bf8d1eafdf)
![23-07-06_6](https://github.com/DesModder/DesModder/assets/67439564/707a9dc6-088c-447b-a678-37b5bf5647b9)
The option label should probably be placed above the number input/slider if this happens

**Comment by FenyLabs** [comment]
Huh, this is weird. I can't reproduce this anymore. CSS updates seem to be quite buggy in Firefox

**Comment by radian628** [comment]
I can't seem to reproduce this either (tested in Edge and Firefox, with "Disable Cache" enabled to make doubly sure). I added some CSS specifically to make the number inputs smaller, so I figure this might be a CSS caching issue on your end. I'm not totally sure yet though.

**Comment by jared-hughes** [comment]
Assuming this is a caching issue, I've made #648.
