### ISSUE TITLE
Intellisense removes character when replacing following token

### ISSUE THREAD

**Issue by SlimRunner** [DesModder/DesModder#666]
Intellisense removes previous character of previous token if replacement occurs on a fully written token with subscript.

Basically create two variables, say A and A_0. Type A and then fully write A_0, but accept Intellisense replacement. After doing so A will disappear.

If the first variable is a token with multiple characters (like sin or a variable with subscript) then only the previous letter is deleted. Here is a video of how to reproduce.

https://github.com/DesModder/DesModder/assets/43660822/02257b7b-9ef4-4a2f-91c1-cfdeac4f287f

**Comment by SlimRunner** [comment]
My bad I forgot to add. I tested on current store release (FF and Chrome) and also in Chrome's latest main build. I did not test any of the current PR branches.

**Comment by radian628** [comment]
This is probably an off-by-one error somewhere (I really need to add tests lol), I'll see what i can do to fix it.

On a more important note, haha funny number (issue #666 lol)

**Comment by SlimRunner** [comment]
I found another one which I think is related. Might be worth testing with #667. I haven't quite gotten it to an atomic case because it was behaving weird (non trivial), but it is now stable. I don't know.

Anyway, here is the graph to test it with. I left comments to describe it, but it deletes a whole frac{}{} token in this case. Earlier it was editing a token ahead.

https://www.desmos.com/calculator/gjwsluzpr7

**Comment by radian628** [comment]
From what I can tell this seems to have a slightly different root cause (looks like having LaTeX both before and after an identifier to be autocompleted causes this bug)
