### ISSUE TITLE
Better Evaluation View hides color swatches

### ISSUE THREAD

**Issue by radian628** [DesModder/DesModder#673]
![image](https://github.com/DesModder/DesModder/assets/70352880/dcc12d7f-3e95-4cc9-bad5-dfd6ea6c2916)
With Better Evaluation View enabled, the color swatch preview for colors disappears. Not sure if this was a bug or if it's intentional. If intentional, it'd be cool if it showed both.

**Comment by FenyLabs** [comment]
The color swatch used to appear, not sure what happened there

**Comment by radian628** [comment]
My best guess would be a breaking change in Desmos itself, but I don't really know for sure.

**Comment by jared-hughes** [comment]
Fixed by 4b290ac8af31398ba7bc3d36f173e9cc63b4acc7
