### ISSUE TITLE
Japanese translation?

### ISSUE THREAD

**Issue by radian628** [DesModder/DesModder#683]
Given the fact that there's a large Japanese math graph art community, it might be good to create a Japanese translation for DesModder. I wouldn't be able to do this as I do not know Japanese, but I'm sure that quite a few people (e.g. ronwnor) do.

**Comment by zukizukizuki** [comment]
I'm Japanese. I would like to implement this translation, where should I translate?

**Comment by radian628** [comment]
Thank you for the offer to translate! All of the translations and the logic that implements them is [here](https://github.com/DesModder/DesModder/tree/main/localization).

To add the translations, you should create a text file called `ja.ftl` in that directory and add the translations there. DesModder uses [Project Fluent](https://projectfluent.org/) for localizations.

To get DesModder to use the translation, edit [this file](https://github.com/DesModder/DesModder/blob/main/localization/i18n-core.ts) to import `ja.ftl` and call `addLanguage` with it at the bottom (in other words copy the code for the other languages, but use the Japanese localization file and language code instead). 

I have to admit I'm not 100% certain that this is _all_ the steps to get this to work (@jared-hughes was the one who set up the internationalization system) but I'm pretty sure this will work.

**Comment by radian628** [comment]
Somehow I didn't notice the README also has an article on this lol. I'll link it here: https://github.com/DesModder/DesModder/blob/main/docs/DEVELOPMENT.md#example-creating-a-new-translation-file

**Comment by zukizukizuki** [comment]
@radian628 
Thank you😊I'll try it.
I will contact you if I have any more questions.
