### ISSUE TITLE
GLesmos: Is this supposed to be in main?

### ISSUE THREAD

**Issue by radian628** [DesModder/DesModder#691]
`c.getContext("invalid")` was just to test lack of webgl2 support right? I'm guessing this was unintentionally left in main.

https://github.com/DesModder/DesModder/commit/19de99cd9fa7d154b17f98982b9d23b26cb93419#diff-56932cb452dbc94ce54b484114d7f82517e1d526ac17e1006d6a1245dc4f10f7R34

**Comment by jared-hughes** [comment]
Thanks for the attentiveness

**Comment by radian628** [comment]
I'll send a PR for a fix (plus a toast that indicates that it's broken)
