### ISSUE TITLE
"Pick a tool to get started" shows over plugins menu in /geometry

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#711]
This would be a good first issue.

![image](https://github.com/DesModder/DesModder/assets/20214911/e5d134f0-23e8-4205-8ea4-c8e7935e26f4)

I suspect the z-index of some element needs to be changed in the CSS.

**Comment by FenyLabs** [comment]
Looking through issues, seems like this was closed in PR 771
