### ISSUE TITLE
Manual line splitting with multiline expressions doesnt work.

### ISSUE THREAD

**Issue by MinekPo1** [DesModder/DesModder#732]
Pressing <kbd>Ctrl+m</kbd> doesnt seem to do anything, not sure why. Thought it is due to firefox having a conflicting keybind, but it doesn't work on chromium either. I've also confirmed the code detects the keypress via a breakpoint.

I'm on linux with wayland, just in case that causes it somehow, but doubt it.

Genuinely no idea what to add here, so bizarre, no errors in the console either.

Maybe I'm reading the plugin description wrong?

**Comment by radian628** [comment]
Btw, to be clear on what that feature is supposed to do, `Ctrl+M` doesn't let you manually insert line breaks wherever you want. It just splits the expressions onto multiple lines the way the plugin would do automatically. It's mainly a lag prevention measure in case someone is working on a slow computer that wouldn't be able to handle multiline's frequent updates.

**Comment by MinekPo1** [comment]
Oh sorry, I must have misunderstood it then. Sorry again! Maybe the text should be made clearer? Possibly "triggered manually" instead of "done manually"?

**Comment by radian628** [comment]
All good, and not your fault! I agree that the text should be clearer. I like "triggered manually."

On a related note, adding in custom line breaking is something I thought impossible, but I've recently realized that there may be a workaround that makes it possible: I can replace groups of spaces (e.g. 3 spaces) with a line break. Few people ever put tons of spaces in their graphs so this'd avoid compatibility headaches, and I could code in custom rules that allow all spaces to be skipped as if they were a single character.

**Comment by radian628** [comment]
Custom line breaks and "triggered manually" should be in the recent 0.12.0 release. As such, I'm gonna close this issue.
