### ISSUE TITLE
Inline Matricies

### ISSUE THREAD

**Issue by GanerCodes** [DesModder/DesModder#738]
\binom{}{} provides something similar, but an option for arbitrary matrices would be really nice.

**Comment by radian628** [comment]
While I like the idea, this is likely out of scope unfortunately since DesModder tries to preserve compatibility with vanilla Desmos (i.e. anything you make in DesModder should run properly for a user who doesn't have DesModder). The only way I could see this working is if the effect is purely visual and/or acts more like syntactic sugar perhaps.

**Comment by GanerCodes** [comment]
> While I like the idea, this is likely out of scope unfortunately since DesModder tries to preserve compatibility with vanilla Desmos (i.e. anything you make in DesModder should run properly for a user who doesn't have DesModder). The only way I could see this working is if the effect is purely visual and/or acts more like syntactic sugar perhaps.

I was thinking it could be some special function or something with rows as arguments in reality and its just rendered nice. I really just use Desmos as an equation writing/editor for my Math classes (I got Dysgraphia irl) and nesting fractions to represent matrices has gotten on my nerves a lot (also a lot of unicode characters turn into two broken characters which is really annoying to traverse through (also the lack of vector arrow and general latex-isms but thats a far secondary)). Honestly if `\binom` just worked for more than 2 rows id be fine cuz i dont mind spacing things out
![image](https://github.com/DesModder/DesModder/assets/34655998/504d165f-ff8c-4f01-b032-18afea6bdcfb)

**Comment by radian628** [comment]
Ahhh so is this more like a visual thing for getting nicely-formatted math as opposed to something that needs to have custom functionality? If that's the case that should prevent essentially all potential vanilla compatibility issues.

I could see this being added as an update to the Multiline Expressions plugin--- for instance you could configure a function to create a newline on every 4th argument (say, if you're trying to make a 4x4 matrix), something like this perhaps:
![image](https://github.com/DesModder/DesModder/assets/70352880/829c1a6c-d6b9-476e-b0c0-befc142ebebf)

**Comment by radian628** [comment]
The more I think about it the more I'm starting to really like the idea of this feature--- occasionally I have to work with complicated functions that group 10+ arguments together so it'd be nice to have a way of organizing them in 2D space.

**Comment by radian628** [comment]
Now the main issue is probably that of getting alignment working between the matrix rows. Unfortunately that's probably the hardest part too unless I employ some sort of cursed `getBoundingClientRect` shenanigans and manually add margins to the commas. A simple `display:grid` or something of that nature wouldn't work unfortunately due to the way the elements are laid out.

**Comment by GanerCodes** [comment]
> Now the main issue is probably that of getting alignment working between the matrix rows. Unfortunately that's probably the hardest part too unless I employ some sort of cursed `getBoundingClientRect` shenanigans and manually add margins to the commas. A simple `display:grid` or something of that nature wouldn't work unfortunately due to the way the elements are laid out.

if its of any use you could do something weird by just removing the borders and changing the """exit actions""" of binoms 
![image](https://github.com/DesModder/DesModder/assets/34655998/af56f2df-1140-45fd-80bc-15e77ee85cb1)

(and if you do add this, which would be awesome, pls give the ability to optionally not have any side-parenthesis/brackets/etc, sometimes i need to stack stuff in general (like a question mark over an arrow or something) so it would be neat)

**Comment by radian628** [comment]
What do you mean by "exit actions"? Like how the arrow keys navigate through the `\binom`s?

**Comment by GanerCodes** [comment]
> What do you mean by "exit actions"? Like how the arrow keys navigate through the `\binom`s?

yeah basically, like hook into how binom handles arrow keys so it moves correctly between them in order to form the matrix (also rn binoms navigate like a flat horizontal list which is annoying, can't go up/down within them)

**Comment by radian628** [comment]
I see, that makes sense. Multiline Expressions has that exact functionality built-in (vertical arrow key navigation), so if I extended that plugin to give more control over where it puts line breaks, it could in theory accomplish something similar.

**Comment by GanerCodes** [comment]
> I see, that makes sense. Multiline Expressions has that exact functionality built-in (vertical arrow key navigation), so if I extended that plugin to give more control over where it puts line breaks, it could in theory accomplish something similar.

yee that would be awesome, honestly for my purposes I'd be down to have document-esque-Desmos, that's sorta a latex editor with desmos formatting/shortcuts built in directly; maybe a button that toggles between math-shortcut mode and text mode. If you look closely on my first screenshot you'll see that I'm sorta doing that already using a bunch of CSS hacks notes and equations look the same so i can align them and stuff, although text has a lot of problems being typed in equation \operatorname{mod}e so i can't just use that lol

**Comment by radian628** [comment]
Hmmm one option that would circumvent the trouble of having to set up a whole system for organizing rows/columns would be to have an invisible no-op sequence you can embed in the LaTeX that is detectable by the plugin but acts as a line break. I could have it be equal to 1 so that you can insert it anywhere in the LaTeX without it having much of an effect (though it may still break in certain cases, like if there's a `+` immediately before it, causing it to act like addition, or if it's the only thing in a summation).

**Comment by radian628** [comment]
The one major downside is that it still has to be fairly short otherwise it'll really break the formatting of non-Desmodder users.

**Comment by radian628** [comment]
Hey, I know! What if multiple consecutive spaces (not sure how many--- maybe 3?) are treated as newlines? That would completely circumvent the issue of the linebreak sequence potentially having some kind of semantic meaning.

**Comment by radian628** [comment]
That being said, this would also cause alignment issues ughhh

**Comment by GanerCodes** [comment]
> Hey, I know! What if multiple consecutive spaces (not sure how many--- maybe 3?) are treated as newlines? That would completely circumvent the issue of the linebreak sequence potentially having some kind of semantic meaning.

https://invisible-characters.com/

**Comment by radian628** [comment]
hopefully I can find one that doesn't cause an error lol

**Comment by radian628** [comment]
Dang, everything I've tried so far (except regular 'ol `0x0020`) has caused an error. One potential workaround would be to just use a comically large number of spaces as a separator to the point where nobody would actually use that many spaces.

**Comment by GanerCodes** [comment]
> Dang, everything I've tried so far (except regular 'ol `0x0020`) has caused an error. One potential workaround would be to just use a comically large number of spaces as a separator to the point where nobody would actually use that many spaces.

would U+1D177 MUSICAL SYMBOL BEGIN SLUR <𝅷> work? It's one of the ones that tries to split itself into two characters in desmos (like e.g. 𝔽 or 𝒫) but it does paste fine

**Comment by radian628** [comment]
Unfortunately U+1D177 doesn't seem to work. I don't think we can fix unicode either sadly because of vanilla compat again. Btw if you're fine with the expressions containing them not graphing properly (which I'm guessing is the case since your use case for Desmos seems to be as a typesetter more than for graphing), I could probably whip up a tampermonkey extension that inserts line breaks at every zero-width joiner or some other whitespace character like that.

**Comment by GanerCodes** [comment]
> Unfortunately U+1D177 doesn't seem to work. I don't think we can fix unicode either sadly because of vanilla compat again. Btw if you're fine with the expressions containing them not graphing properly (which I'm guessing is the case since your use case for Desmos seems to be as a typesetter more than for graphing), I could probably whip up a tampermonkey extension that inserts line breaks at every zero-width joiner or some other whitespace character like that.

I mean unicode renders find in Desmos, I just want to be able to traverse/backspace/write(I can only paste them, if i type out special unicode chars via like xcompose it just refuses on Desmos) it without it decomposing into multiple characters lol.
Really the dream for me is a plugin or extension that hide fraction lines when a fraction is immediately after a zero-width joiner, that would make my day

**Comment by radian628** [comment]
> Really the dream for me is a plugin or extension that hide fraction lines when a fraction is immediately after a zero-width joiner, that would make my day

This sounds doable to me as a tampermonkey extension. Idk about main DesModder since I don't want to break graphing, but I could probably whip up a tampermonkey userscript in a bit that hides fraction lines when they're after zero-width joiners.

**Comment by GanerCodes** [comment]
> > Really the dream for me is a plugin or extension that hide fraction lines when a fraction is immediately after a zero-width joiner, that would make my day
> 
> This sounds doable to me as a tampermonkey extension. Idk about main DesModder since I don't want to break graphing, but I could probably whip up a tampermonkey userscript in a bit that hides fraction lines when they're after zero-width joiners.

yeah that would be absolutely amazing, hmu if you ever get around to doing it :D

**Comment by radian628** [comment]
Alright there we go, this should hopefully work:

```js
// ==UserScript==
// @name         Desmos ZWJ Fraction Bar Hider
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Hide brackets in Desmos Graphing Calculator.
// @author       radian628
// @match        *://*.desmos.com/**
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    function hideAfterSpace(elem) {
        const children = elem.children;

        for (let i = 0; i < children.length - 1; i++) {
            const frac = children[i];
            const zwj = children[i+1].classList.contains("dcg-mq-cursor") ? children[i+2] : children[i + 1];

            if (zwj && zwj.innerText === "\u200D" && frac.classList.contains("dcg-mq-fraction")) {
                frac.children[1].style.border = "none";
            }
        }

        for (const child of elem.children) hideAfterSpace(child);
    }

    function hideAllAfterSpace() {
        const rootblocks = document.querySelectorAll(".dcg-mq-root-block");

        for (const rb of rootblocks) hideAfterSpace(rb);

    }

    const interval = setInterval(() => {
        if (window.Calc) {
            hideAllAfterSpace();
            clearInterval(interval);
            Calc.controller.dispatcher.register(e => {
                if (e.type === "set-item-latex") {
                    console.log("got here");
                    hideAllAfterSpace();
                }
            });
        }
    })

    // Your code here...
})();
```

I decided to make the fraction bar go away when the ZWJ is *after* the fraction. I found that if I configure it to work when the ZWJ is *before*, you run into an issue where it gets stuffed into the numerator along with whatever number is in the numerator unless you're careful to avoid that. There's no such issue putting the ZWJ after the fraction.

**Comment by radian628** [comment]
> Although when I reload the graph I gotta sorta "interact" with an equation to make the fraction bar re-dissappear- is there any particular reason this is?

Hmm, looks like I can fix that by listening for `set-state` events. Here's a fix:

```js
// ==UserScript==
// @name         Desmos ZWJ Fraction Bar Hider
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Hide brackets in Desmos Graphing Calculator.
// @author       radian628
// @match        *://*.desmos.com/**
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    function hideAfterSpace(elem) {
        const children = elem.children;

        for (let i = 0; i < children.length - 1; i++) {
            const frac = children[i];
            const zwj = children[i+1].classList.contains("dcg-mq-cursor") ? children[i+2] : children[i + 1];

            if (zwj && zwj.innerText === "\u200D" && frac.classList.contains("dcg-mq-fraction")) {
                frac.children[1].style.border = "none";
            }
        }

        for (const child of elem.children) hideAfterSpace(child);
    }

    function hideAllAfterSpace() {
        const rootblocks = document.querySelectorAll(".dcg-mq-root-block");

        for (const rb of rootblocks) hideAfterSpace(rb);

    }

    const interval = setInterval(() => {
        if (window.Calc) {
            hideAllAfterSpace();
            clearInterval(interval);
            Calc.controller.dispatcher.register(e => {
                if (e.type === "set-item-latex" || e.type === "set-state") {
                    console.log("got here");
                    setTimeout(() => hideAllAfterSpace());
                }
            });
        }
    })

    // Your code here...
})();
```

**Comment by GanerCodes** [comment]
That didn't fix it but i just removed the condition on the if statement and that fixed it lol

**Comment by GanerCodes** [comment]
ok i did some more work and fixed some of the unicode stuff. I can now type multiglyph letters natively into Desmos which is a massive time savior over doing ctrl+t→*sequence*→ctrl+a→ctrl+x→ctrl+w→ctrl+v

```javascript
// ==UserScript==
// @name         Desmos Swagger
// @namespace    http://tampermonkey.net/
// @version      0.1000000001
// @description  Hide brackets in Desmos Graphing Calculator.
// @author       radian628, Ganer
// @match        *://*.desmos.com/**
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    function hideAfterSpace(elem) {
        const children = elem.children;

        for (let i = 0; i < children.length - 1; i++) {
            const frac = children[i];
            const zwj = children[i+1].classList.contains("dcg-mq-cursor") ? children[i+2] : children[i + 1];

            if (zwj && zwj.innerText === "\u200D" && frac.classList.contains("dcg-mq-fraction")) {
                frac.children[1].style["border-top"] = "1px solid transparent";
            }
        }

        for (const child of elem.children) hideAfterSpace(child);
    }
    
    function writeMultichar(e) {
        (e.data.length <= 1) || Calc.focusedMathQuill.write(e.data)
    }

    function expressionMod() {
        document.querySelectorAll(".dcg-mq-root-block").forEach(hideAfterSpace);
        document.querySelectorAll(".dcg-mq-textarea > textarea").forEach(z => z.oninput = writeMultichar);
    }

    const interval = setInterval(() => {
        if (window.Calc) {
            expressionMod();
            clearInterval(interval);
            Calc.controller.dispatcher.register(e => {
                if(e.type == "tick") return;
                setTimeout(() => expressionMod());
            });
        }
    })
})();
```

**Comment by radian628** [comment]
Seems like this userscript fixed the problem, so I'm gonna close the issue now.

**Comment by radian628** [comment]
![image](https://github.com/DesModder/DesModder/assets/70352880/b0f0107f-356b-474d-96c2-7bce328e82f4)

ik this is closed, but I thought you might find this WIP multiline feature interesting

**Comment by GanerCodes** [comment]
> ![image](https://user-images.githubusercontent.com/70352880/273684250-b0f0107f-356b-474d-96c2-7bce328e82f4.png)
> 
> ik this is closed, but I thought you might find this WIP multiline feature interesting

It's really cool! There's a few problems however that doesn't make it work for me; for one I can't indent things over b/c shift+enter doesn't work unless you have triple space replace enabled which messes up the indent; maybe another joiner trick to be used? I also can't navigate vertically with up/down, and text and stuff flashes/moves sometimes

**Comment by radian628** [comment]
Joiner trick would be nice but sadly I likely won't put that in official DesModder since it breaks graphing. Btw the feature I posted (automatic centering of grids) isn't out yet, but once it is it should hopefully mean you don't have to manually align stuff at all anymore.
