### ISSUE TITLE
Use Desmos's GLSL emit target instead of hand-rolling

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#746]
Now that Desmos supports GLSL as an emit target, we don't need `compileGLesmos`, `emitChunkGL`, `exportAsGLesmos`, etc.

The could be in a few steps (might skip over step 1 entirely and just be in step 2 as long as desired):
1. enable Desmos's compiler, but only if the user enables it in settings (i.e. default OLD)
2. enable Desmos's compiler by default, but allow for it to be disabled (i.e. default NEW)
3. remove the old compiler entirely (there is no rush to get to this step)

Supported here but not Desmos's compiler:
- different list length limit?
- factorial not yet supported in Desmos
- Not sure what else GLesmos supports but Desmos does not.

Would be fixed by switching to Desmos's compiler
-  0^0 #467
- old code #315
- NaN * 0 #314
- many other floating point issues that I hadn't noticed in GLesmos.

Not supported in Desmos's compiler or here, but would be better fixed in Desmos instead of here:
- List filters #510

**Comment by FenyLabs** [comment]
I would say start in step 2. I also hope the safety features in the Desmos compiler could let us keep glesmos on through page reload.

**Comment by jared-hughes** [comment]
There's no extra safety features that protect against long computations that would freeze the page.
