### ISSUE TITLE
Pull in @desmodder/graph-state

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#755]
It's fallen behind. Better to monorepo it.

Expected workflow with separate repository. E.g. want to add `speed3D` info:
1. edit the other repository
2. release on npm
3. update in this repository

Actual workflow:
1. Give up and use `as any`

Workflow with monorepo:
1. Edit it directly.

**Comment by FenyLabs** [comment]
Makes sense since we have a monorepo now anyway

**Comment by jared-hughes** [comment]
Done in #801
