### ISSUE TITLE
Debug mode to show expression IDs instead of indices

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#77]
This would help for external scripts, such as https://github.com/jason-woolf/DesmosPlayer, where the user might want the expression IDs. Other use cases include writing scripts to generate a bunch of expressions into a folder; the author of the script would want to know the folder ID.

![image](https://user-images.githubusercontent.com/20214911/117078604-08384a00-acef-11eb-9bbb-33b37bf137b1.png)

Care must be taken to ensure this still works when searching expressions and after toggling the expressions list.

Maybe also allow editing the expression IDs (to serve as labels), though that is a tricky business because IDs are supposed to be invariant.

**Comment by Scoder12** [comment]
Maybe it can display the expression number and the ID at the same time

**Comment by jared-hughes** [comment]
That could get cluttered quickly, especially for expressions that don't leave much space in the left tab area (https://www.desmos.com/calculator/uxiv72aken?nolabels).

It could be better to show the ID above the "Lines" text at the top of the expression options menu that you get from right-clicking on the style circle:
![image](https://user-images.githubusercontent.com/20214911/118581450-87456d80-b746-11eb-9f6a-a952a6114f89.png)

This could also give space to let the ID be editable if desired.

My only concern here is that expressions with an error do not let you access the expression options menu. Maybe the ID could show on tooltip, but I do not think that is a priority.
