### ISSUE TITLE
Intellisense: Bug that prevents you from typing `.` s

### ISSUE THREAD

**Issue by radian628** [DesModder/DesModder#783]
I was able to reproduce this bug with this graph: https://www.desmos.com/calculator/eipggprxqp

Try typing a `.` into this expression. It won't type anything.
![image](https://github.com/DesModder/DesModder/assets/70352880/d265c358-defd-444c-83f8-c70b642be8aa)

**Comment by SlimRunner** [comment]
Probably you've already found out, but just in case on my end this only happens when you have the Auto-Subscriptify setting enabled.

**Comment by jared-hughes** [comment]
Fixed by https://github.com/DesModder/DesModder/pull/823.

By the way @SlimRunner, it was helpful to have your note about Auto-Subscriptify being important. Thanks.
