### ISSUE TITLE
Matrix multiplication

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#86]
This could be just syntactic sugar, but it could work decently-well in transforming points.

**Comment by FabriceNeyret** [comment]
but this is the kind of feature that would make graphs no longer working to people not having the plugin.
If you really want to make an extension of math features (not compatible with vanilla Desmos), I suggest to make a dedicated separate plugin for that, or confusions might result, and a chaos of not-compatible graphs without people knowing it. (worse: just a part might be broken in some folder, people will just see something without knowing it's not the right thing).

**Comment by jared-hughes** [comment]
Yes, these concerns are valid, but I should clarify what I mean.

This would only be syntactic sugar, A DesModder user would write something like `a = (1 1 ; 0 1) * b` to apply a skew matrix, and they would see it all written out in pretty matrix notation. However, a vanilla user would see instead `a = (1*b.x + 1*b.y, 0*b.x, 1*b.y)`, so it would remain compatible.

See also https://github.com/jared-hughes/DesModder/issues/24, in which a DesModder user could write `a≠b`, and vanilla users would see `{a=b,0}=0`

**Comment by FabriceNeyret** [comment]
wow, I see: the user type the new syntax, he see it like he typed it, but in facts you store the compatible version.
Ghost feature. genius ! :-)

**Comment by jared-hughes** [comment]
@MasterOfBob777 raises the point in #206 that the [Desmos matrix calculator](https://www.desmos.com/matrix) exists. This could be a good source for UI.
