### ISSUE TITLE
Include certain settings in shared graph URLs

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#87]
See https://www.reddit.com/r/desmos/comments/nbbq27/new_feature_discovery_query_parameters/

A few that seem most helpful are:
- ?lockViewport
- ?invertedColors
- ?expressionsCollapsed, but that doesn't seem to work
- maybe: ?textColor and ?backgroundColor
- just going off the top of my head, so there may be more

Such a plugin would
- change the link in the share menu (similar to how language is included)
- change the link in the URL bar to include the additional query parameters

**Comment by FabriceNeyret** [comment]
what about the 2 perfs setting ? ( these are the most useful to me ;-) )
NB: for now inserting then as ?parameter is not compatible with the plugin.
( BTW, probably the plugin should let the explicit parameters override him )

**Comment by jared-hughes** [comment]
> probably the plugin should let the explicit parameters override him

See https://github.com/jared-hughes/desmodder-builtin-settings/issues/3

That issue is also relevant to this issue of including the settings in shared URLs

**Comment by jared-hughes** [comment]
Closed for the same reason as #101
