### ISSUE TITLE
Video creator has stopped working

### ISSUE THREAD

**Issue by codebubs** [DesModder/DesModder#881]
It looks like the video creator menu doesn't open in Desmos anymore. I first observed this issue on Thursday, May 29th at around 8:30 PM UTC. When trying to open the menu, I see "FFmpeg is loading...". Then, the menu closes and doesn't open again until I reload Desmos, upon which the cycle repeats.
![image](https://github.com/DesModder/DesModder/assets/63488677/b2361814-2948-473d-99eb-f0e3b5ffffef)
![image](https://github.com/DesModder/DesModder/assets/63488677/86459ac7-7205-46f8-a3ee-93a140bf3b14)
As shown in the above images, there is still a small triangle visible when trying to open the menu, but the rest of the menu remains unseen.

**Comment by jared-hughes** [comment]
Sorry! The fix will be out soon. Something changed inside Desmos that broke this

**Comment by jared-hughes** [comment]
The fix is out in Firefox. If you want it now in Chrome, you can follow the advanced instructions in https://www.desmodder.com/installation.
