### ISSUE TITLE
Migrating to a DesModder Organization

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#91]
I see a few advantages to migrating to a Github Organization:
 - better organization of the plugin repositories so they can be more easily found
 - ability to make a http://desmodder.github.io/ if that would ever be helpful
 - organization-wide Project boards

I already made https://github.com/DesModder just to reserve the name :)

My question is: are there any downsides to migrating the repositories to a GH Organization?

**Comment by Scoder12** [comment]
Only downside would be that you would have to transfer the repos in but that is a one-time job.
