### ISSUE TITLE
Add option for enabling complex number support.

### ISSUE THREAD

**Issue by spidunno** [DesModder/DesModder#934]
I'm not familiar with the codebase of DesModder, but I recently figured out how to enable what seems like experimental complex number support in Desmos. It needs to be done very early on in the initialization of the Calculator object, but if you set `Calc.controller.graphSettings.config.allowComplex = true` right when the calculator initializes (or just pass it in as `true` in the config object for the Calculator constructor), it enables this switch:

![image](https://github.com/user-attachments/assets/a4a65ea6-9603-4abf-bb17-e34b9a229cb9)

From my testing it appears to work pretty well too.

![image](https://github.com/user-attachments/assets/c6b1587f-26a9-4df4-bea5-10d1a7146509)

**Comment by spidunno** [comment]
Seems like it would be pretty simple, just adding something to settingsConfigList in https://github.com/DesModder/DesModder/blob/main/src/plugins/builtin-settings/config.ts like

```ts
{
    key: "allowComplex",
    type: "boolean",
    default: false,
 }
 ```

**Comment by jared-hughes** [comment]
Not planned, sorry. It will come out when it comes out (hopefully soon).
