### ISSUE TITLE
Doesn't Show Up on Main Site, Clicking on Extension Gives Broken Page

### ISSUE THREAD

**Issue by Hollywood42** [DesModder/DesModder#970]
It's been a week or two since I've been on desmos but now when I enter a graph the desmodder tools don't pop up on the side. And if I click directly on the extension it brings me to the page shown below which is useless and crashes if I try and type anything. Anyone else have the same issue/a fix? Same issue on Firefox, Chrome, and Edge. 
![image](https://github.com/user-attachments/assets/70451b62-34b3-4a1b-90cc-9e413566bfb9)

**Comment by jared-hughes** [comment]
Everyone should be having the same issue with respect to DesModder not loading. There was a very recent change in Desmos that broke it. The split mega-broken page seems to only occur on sufficiently slow networks; I have to throttle in the Network tab of devtools to "Fast 4G" to get it. The reason there is that DesModder is failing to block the initial load of Desmos, but it doesn't know that until Desmos actually loads. If Desmos takes longer to load than DesModder, then DesModder can't know at the time of loading that Desmos _will_ load again.

**Comment by jared-hughes** [comment]
This is included as part of DesModder v0.14.1, now released on Firefox, pending approval in Chrome.

**Comment by Hollywood42** [comment]
Thank you for the quick fix!
